name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_APP_EMAIL}}
          appdir: "server"
          usedocker: true
        env:
          HD_MONGO_Vikki: ${{secrets.MONGO_VIKKI}}
          HD_SECRET: ${{secrets.SECRET}}
          HD_JWT_KEY: ${{secrets.JWT_KEY}}
          HD_STRIPE_SKEY: ${{secrets.STRIPE_SKEY}}
          HD_EMAIL: ${{secrets.EMAIL}}
          HD_PASSWORD: ${{secrets.PASSWORD}}
          HD_RESET_PASSWORD_KEY: ${{secrets.RESET_PASSWORD_KEY}}
